grafana:
  adminPassword: admin
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus:9090
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUpdates: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      otel-metrics:
        url: https://grafana.com/api/dashboards/12114/revisions/1/download

  service:
    type: ClusterIP
    port: 3000

